### ISSUE TITLE
Remove .idea from the repository and add a .gitignore file.

### ISSUE THREAD

**Issue by TrevorVonSeggern** [DaveKerk/Cloud-Code#1]
.idea directory is user specific and is a little better if it is not the the repository as it contains your personal settings.
Example .gitignore for you to use...
.idea
archive
node_modules
bower_components
dist
npm-debug.log
iisnode

**Comment by DaveKerk** [comment]
Fixed.

**Comment by TrevorVonSeggern** [comment]
Nice!
